spring:
  rabbitmq:
    host: 54.180.82.61
    port: 5672
    username : daily-mission-admin
    password : minholee93
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual

server:
  port: 8081