spring:
  rabbitmq:
    host: 15.164.97.2
    port: 5672
    username : daily-mission-admin
    password : minholee93
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
server:
  port: 8081