spring:
  rabbitmq:
    host: 13.209.6.233
    port: 5672
    username : daily-mission-admin
    password : minholee93
    listener:
      direct:
        acknowledge-mode: manual
      simple:
        acknowledge-mode: manual
        retry:
          enabled: true
          initial-interval: 3s
          max-interval: 10s
          max-attempts: 5
          multiplier: 2
server:
  port: 8081
